### ISSUE TITLE
Constraining it and downloading with onclick

### ISSUE THREAD

**Issue by secretgspot** [manuel3108/pdfsvex#29]
How would I go about constraining to a size when I import it to an existent page as a component instead of it filling whole window?  How could I download pdf when button clicked?

**Comment by manuel3108** [comment]
Hey there,

I don't think there is any way to achieve what you want at this point. 
This small repo / lib was written in accomodations to my thesis, so the main purpose was to display it full screen

**Comment by secretgspot** [comment]
k
